services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: genotes-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data/chromadb:/app/data/chromadb
      - ./data/datasets:/app/data/datasets
      - ./backend:/app/backend
    env_file:
      - .env
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - CHROMA_DB_PATH=/app/data/chromadb
      - DATASETS_PATH=/app/data/datasets
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - genotes-network
    depends_on:
      - ollama
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: genotes-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - genotes-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:1.25.3-alpine
    container_name: genotes-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - genotes-network
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ollama:
    image: ollama/ollama:latest
    container_name: genotes-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - genotes-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  ollama_data:
    name: genotes-ollama-data

networks:
  genotes-network:
    driver: bridge
